sudo: required
services:
  - docker

before_install:
  - docker build -t saharnab99/docker-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true saharnab99/docker-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-aws"
  env: "DockerAws-env"
  bucket_name: "elasticbeanstalk-ap-south-1-024497252280"
  bucket_path: "docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
